name: mtproj
description: CLI command tools for my personal projects.
version: 0.1.0
homepage: https://github.com/mtorreao/mtproj
author: Matheus Torreão <mtorreao1@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.2
  yaml: ^2.1.16
  args: ^1.5.2
  pubspec: ^0.1.1
  http: ^0.12.0+2
  dio: ^3.0.3
  dotenv: ^1.0.0
  graphql: ^2.1.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

executables:
  mtproj: main
